pdftotext=/cygdrive/d/poppler-26.02.0/Library/bin/pdftotext.exe

"$pdftotext"  "chrome-bizud-all.pdf" "chrome-bizud-all pdftotext.txt"
"$pdftotext"  "chrome-bizud-limit.pdf" "chrome-bizud-limit pdftotext.txt"
"$pdftotext"  "chrome-bizud-all-MM.pdf" "chrome-bizud-all-MM pdftotext.txt"
"$pdftotext"  "chrome-bizud-limit-MM.pdf" "chrome-bizud-limit-MM pdftotext.txt"
"$pdftotext"  "chrome-line-all.pdf" "chrome-line-all pdftotext.txt"
"$pdftotext"  "chrome-line-limit.pdf" "chrome-line-limit pdftotext.txt"
"$pdftotext"  "chrome-line-all-MM.pdf" "chrome-line-all-MM pdftotext.txt"
"$pdftotext"  "chrome-line-limit-MM.pdf" "chrome-line-limit-MM pdftotext.txt"
"$pdftotext"  "chrome-mplus-all.pdf" "chrome-mplus-all pdftotext.txt"
"$pdftotext"  "chrome-mplus-limit.pdf" "chrome-mplus-limit pdftotext.txt"
"$pdftotext"  "chrome-mplus-all-MM.pdf" "chrome-mplus-all-MM pdftotext.txt"
"$pdftotext"  "chrome-mplus-limit-MM.pdf" "chrome-mplus-limit-MM pdftotext.txt"
"$pdftotext"  "chrome-noto-all.pdf" "chrome-noto-all pdftotext.txt"
"$pdftotext"  "chrome-noto-limit.pdf" "chrome-noto-limit pdftotext.txt"
"$pdftotext"  "chrome-noto-all-MM.pdf" "chrome-noto-all-MM pdftotext.txt"
"$pdftotext"  "chrome-noto-limit-MM.pdf" "chrome-noto-limit-MM pdftotext.txt"
"$pdftotext"  "firefox-bizud-all.pdf" "firefox-bizud-all pdftotext.txt"
"$pdftotext"  "firefox-bizud-limit.pdf" "firefox-bizud-limit pdftotext.txt"
"$pdftotext"  "firefox-line-all.pdf" "firefox-line-all pdftotext.txt"
"$pdftotext"  "firefox-line-limit.pdf" "firefox-line-limit pdftotext.txt"
"$pdftotext"  "firefox-mplus-all.pdf" "firefox-mplus-all pdftotext.txt"
"$pdftotext"  "firefox-mplus-limit.pdf" "firefox-mplus-limit pdftotext.txt"
"$pdftotext"  "firefox-noto-all.pdf" "firefox-noto-all pdftotext.txt"
"$pdftotext"  "firefox-noto-limit.pdf" "firefox-noto-limit pdftotext.txt"
