<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <WarnOn>3390;$(WarnOn)</WarnOn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DataTypes.fs" />
    <Compile Include="ReportTypes.fs" />
    <Compile Include="MappingLoader.fs" />
    <Compile Include="CMapParser.fs" />
    <Compile Include="Analyzer.fs" />
    <Compile Include="ReportGenerator.fs" />
    <Compile Include="BatchProcessor.fs" />
    <Compile Include="TextAccessibilityChecker.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="data\DerivedNormalizationProps.txt" />
    <EmbeddedResource Include="data\EquivalentUnifiedIdeograph.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
  </ItemGroup>

</Project>